### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by KalobTaulien** [EdmontonPy/edmontonpy#5]
This site _needs_ a TLS certificate. Letsencrypt offers a free certs. Or if you route through CloudFlare you can get a free one (but it only secures half the line).

@data-get maybe you can add this?

**Comment by dgmouris** [comment]
@KalobTaulien I think this should be an issue on https://github.com/EdmontonPy/edmontonpy-ops as well.

**Comment by KalobTaulien** [comment]
Yep, you're right, I forgot that repo existed.
