### ISSUE TITLE
More .gitignore support

### ISSUE THREAD

**Issue by KalobTaulien** [EdmontonPy/edmontonpy#7]
Lots of devs work on different operating systems and editors. I think we can keep out lots of unwanted files by ignoring more files. 

We should consider ignoring temporary files, OS generated files and editor files. Along with any additional python cache we might run into, like mypy.

**Comment by data-get** [comment]
Agreed that this would be great. I won't be going out of my way and adding files that the community does not identify need to be ignored. I've added what my development environment created. I would gladly accept pull requests that included what other peoples environments create.

**Comment by data-get** [comment]
See: #9
