### ISSUE TITLE
Sponsor images are too close together on mobile.

### ISSUE THREAD

**Issue by dgmouris** [EdmontonPy/edmontonpy#8]
I think that the images need a bit of space for a better experience.

Here is what it looks like on mobile.

![WhatsApp Image 2019-03-13 at 3 27 48 PM](https://user-images.githubusercontent.com/8164434/54316206-c9daf080-45a5-11e9-963c-2a7321fc1cf7.jpeg)

**Comment by dgmouris** [comment]
PS. This was on a Google Pixel 2 phone, it looks a bit different on Iphones...

**Comment by data-get** [comment]
https://github.com/EdmontonPy/edmontonpy/pull/32
